### ISSUE TITLE
Hmmm

### ISSUE THREAD

**Issue by DataRaptor** [jarry-xiao/logspammer#1]
Hmmm interesting lol. 

Thought about this too but always assumed that the total cost of storing these logs < the fee by the tx payer (reward + burn)? 

If that's true then this is fine no? But if not, then that seems problematic. 

Or is there another way that you're thinking about this? 

Also, I like your rust clients :) 

- Luigi (We met at Jump)

**Comment by jarry-xiao** [comment]
nope --  you can use this truncate the logs of any program that relies on normal logs to store data

**Comment by DataRaptor** [comment]
Ahhh I see. Log truncation sucks for events. 

So this attack is basically: 

1) You have some system that depends on some off-chain log/event propagation, tied to a protocol. The protocol ensures that logs are small enough to not be truncated. 

2) Construct protocol ix, drop that spam ix in there, then their systems break.

**Comment by jarry-xiao** [comment]
yep exactly -- any reliability on program logs is vulnerable to an attack like this

The only ways that I know of to prevent this are using the `set_return_data` syscall or making a CPI to a downstream contract and storing the logs in the instruction data. I prefer the latter

**Comment by DataRaptor** [comment]
Innnteresting. I don't fully understand the former. But the latter makes sense to me. Perhaps this should be included in the prog-library. Also in favour of adding an ix to the system_program (But I can imagine that's basically impossible to approve). Would help with not having to pass in an extra pubkey for the log program :P

In the context of anchor, also seen some hacky solutions that work where people poll their program's transaction histories or listen to the program address and parse the program logs with the anchor Coder. Seems like you can reconstruct all the events you missed if you do that.
